spring.application.name=multiplayer-chess

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.datasource.url=jdbc:postgresql://localhost:5433/multiplayer_chess
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=8080